name: Debug Secrets for GCP Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Debug GCP_PROJECT_ID
    - name: Debug GCP_PROJECT_ID
      run: echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}"

    # Step 3: Debug Full Docker Tag
    - name: Debug Full Docker Tag
      run: echo "Docker Tag: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest"

    # Step 4: Verify Docker is Installed
    - name: Check Docker Version
      run: docker --version

    # Step 5: Build and Push Docker Image (Optional - Uncomment for additional testing)
    # Uncomment this step if you want to test the image build while debugging
    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest .
    #     docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest



# name: Deploy to Google Cloud Run

# on:
#   push:
#     branches:
#       - main  # Trigger workflow on pushes to the 'main' branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Checkout the repository
#     - name: Checkout code
#       uses: actions/checkout@v3

#     # Step 2: Set up Google Cloud SDK
#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v1
#       with:
#         project_id: ${{ secrets.GCP_PROJECT_ID }}
#         service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

#     # Step 3: Authenticate Docker with GCP
#     - name: Authenticate Docker with GCP
#       run: gcloud auth configure-docker

#     # Step 4: Build and Push Docker Image
#     - name: Build and Push Docker Image
#       run: |
#         docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest .
#         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest

#     # Step 5: Deploy to Google Cloud Run
#     - name: Deploy to Cloud Run
#       run: |
#         gcloud run deploy flask-api \
#           --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest \
#           --region ${{ secrets.GCP_REGION }} \
#           --platform managed \
#           --allow-unauthenticated
