name: Debug Secrets for GCP Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Debug GCP_PROJECT_ID
    - name: Debug GCP_PROJECT_ID
      run: echo "GCP_PROJECT_ID is: ${{ secrets.GCP_PROJECT_ID }}"

    # Step 3: Debug Full Docker Tag
    - name: Debug Full Docker Tag
      run: |
        DOCKER_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest"
        echo "Docker Tag is: $DOCKER_TAG"

    # Step 4: Verify Docker Installation
    - name: Check Docker Version
      run: docker --version